---
- name: Initialize Ansible Host
  hosts: ansible_host
  become: yes
  roles:
    - ansible-host
  tags:
    - never
    - ansible

- name: Linux
  hosts: linux
  become: yes
  roles:
    - linux
  tags:
    - never
    - linux

- name: Windows
  hosts: windows
  roles:
    - windows
  tags:
    - never
    - windows