---
- name: Set Wazuh IP Fact
  hosts: windows:linux:wazuh
  gather_facts: no
  tasks:
    - set_fact:
        wazuh_ip: "{{ hostvars['logging'].ansible_host }}"

- name: Initialize Ansible Host
  hosts: ansible_host
  become: yes
  roles:
    - ansible-host
  tags:
    - never
    - ansible

- name: Linux
  hosts: linux
  become: yes
  roles:
    - linux
  tags:
    - never
    - linux

- name: Windows
  hosts: windows
  roles:
    - windows
  tags:
    - never
    - windows

- name: Logging
  hosts: logging
  become: yes
  roles:
    - logging
  tags:
    - never
    - wazuh