---
- name: Set Wazuh IP Fact
  hosts: all
  gather_facts: no
  tasks:
    - set_fact:
        wazuh_ip: 192.168.1.95
  tags:
    - always
    - linux
    - windows
    - logging

- name: Initialize Ansible Host
  hosts: local_host
  become: yes
  roles:
    - ansible-host
  tags:
    - never
    - ansible

- name: Linux
  hosts: linux
  become: yes
  roles:
    - linux
  tags:
    - never
    - linux

- name: Windows
  hosts: windows
  roles:
    - windows
  tags:
    - never
    - windows

- name: Logging
  hosts: logging
  become: yes
  roles:
    - logging
  tags:
    - never
    - wazuh