---
- name: Set Wazuh IP Fact
  set_fact:
    wazuh_ip: '192.168.1.73' #TODO DURING COMP

- name: Drop SSH Key for root user
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/opt/inventory/id_rsa.pub') }}"

# - name: Disable Password Authentication
#   lineinfile:
#     path: /etc/ssh/sshd_config
#     regexp: '^#?PasswordAuthentication'
#     line: 'PasswordAuthentication no'
#     state: present
#     backup: yes
  
# - name: Restart SSH
#   service:
#     name: sshd
#     state: restarted

- name: Make Linux Scripts Directory
  file:
    path: /usr/src/scripts
    state: directory

- name: Download Backup Script
  get_url:
    url: https://raw.githubusercontent.com/CCDC-RIT/Linux-Scripts/main/Initial/backups.sh
    dest: /usr/src/scripts/backups.sh
    force: yes
    mode: 0755
  
- name: Run Backup Script
  shell: /usr/src/scripts/backups.sh
  become: yes

- name: Download downloads script
  get_url:
    url: https://raw.githubusercontent.com/CCDC-RIT/Linux-Scripts/main/Initial/downloads.sh
    dest: /usr/src/scripts/downloads.sh
    force: yes
    mode: 0755

- name: Run Downloads Script
  shell: cd /usr/src/scripts/ && /usr/src/scripts/downloads.sh
  become: yes

- name: Run OS Detection
  shell: cd /usr/src/scripts/Linux-Scripts/Initial && /usr/src/scripts/Linux-Scripts/Initial/os_detection.sh

- name: Run Inventory Script
  shell: cd /usr/src/scripts/Linux-Scripts/Initial && /usr/src/scripts/Linux-Scripts/Initial/inventory.sh | tee /usr/src/scripts/inventory.txt
  register: inventory

- name: Store Inventory Script Output onto local Ansible Box
  fetch:
    src: /usr/src/scripts/inventory.txt
    dest: /opt/inventory/{{ ansible_hostname }}-inventory.txt
    flat: yes
    fail_on_missing: no

- name: Run Logging Script
  shell: cd /usr/src/scripts/Linux-Scripts/Logging && echo -e '{{ wazuh_ip }}' | /usr/src/scripts/Linux-Scripts/Logging/setup_logging.sh

- name: Run Hardening Script
  shell: "cd /usr/src/scripts/Linux-Scripts/Initial && /usr/src/scripts/Linux-Scripts/Initial/Hardening Script/hardening.sh"

# first downloads script
# inventory script - store locally and on ansible box