---
- name: Set Current User Fact
  local_action: command whoami
  register: current_user

- name: Create Inventory Directory
  file:
    path: /opt/inventory
    state: directory
    mode: 0777

- name: Create Audit Directory
  file:
    path: /opt/audit
    state: directory

- name: Create SSH Key
  openssh_keypair:
    path: /opt/inventory/id_rsa
    force: yes
    owner: '{{ current_user.stdout }}'
