---
- name: Install Git
  apt:
    name: ['git', 'curl']
    state: present

- name: Git Clone Repo
  git:
    repo: https://github.com/CCDC-RIT/Logging-Scripts.git
    dest: /opt/Logging-Scripts
    force: yes

- name: Chmod Permissions for all scripts
  shell: cd /opt/Logging-Scripts && chmod 755 *.sh

- name: Run Wazuh Manager Setup Script
  shell: cd /opt/Logging-Scripts && bash /opt/Logging-Scripts/wazuh-manager.sh
  ignore_errors: yes