---
- name: Ask for Wazuh IP
  pause:
    prompt: "What is the IP of the Wazuh Box:"
  register: wazuh_ip
  
# - name: Create Epic Games and Fortnite Directories
#   ansible.windows.win_file:
#     path: C:\ProgramData\EpicGames\Fortnite
#     state: directory

# - name: Disable Script Execution Policy
#   ansible.windows.win_shell: Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force

# - name: Get Downloads Script
#   ansible.windows.win_get_url:
#     url: https://raw.githubusercontent.com/CCDC-RIT/Windows-Scripts/master/downloads.ps1
#     dest: C:\ProgramData\EpicGames\Fortnite\downloads.ps1
#     force: yes

# - name: Run Downloads Script
#   ansible.windows.win_shell: C:\ProgramData\EpicGames\Fortnite\downloads.ps1 -Path C:\ProgramData\EpicGames\Fortnite\

# - name: Run Inventory Script and Store Output Locally
#   ansible.windows.win_shell: C:\ProgramData\EpicGames\Fortnite\scripts\inventory.ps1
#   register: inventory

# - name: Store Inventory Script Output onto local Ansible Box
#   ansible.builtin.fetch:
#     src: C:\ProgramData\EpicGames\Fortnite\scripts\results\inventory.txt
#     dest: /opt/inventory/{{ ansible_hostname }}-inventory.txt
#     force: yes

# - name: Run Audit Script
#   ansible.windows.win_shell: C:\ProgramData\EpicGames\Fortnite\scripts\audit.ps1

- name: Run Logging Script with Wazuh Box's IP 
  ansible.windows.win_shell: C:\ProgramData\EpicGames\Fortnite\scripts\logging.ps1 {{ wazuh_ip }}

- name: Run Backup Script
  ansible.windows.win_shell: C:\ProgramData\EpicGames\Fortnite\scripts\backup.ps1