---
- name: Create Epic Games and Fortnite Directories
  ansible.windows.win_file:
    path: C:\ProgramData\EpicGames\Fortnite
    state: directory

- name: Get Downloads Script
  ansible.windows.win_get_url:
    url: https://raw.githubusercontent.com/CCDC-RIT/Windows-Scripts/master/downloads.ps1
    dest: C:\ProgramData\EpicGames\Fortnite\downloads.ps1
    force: yes

- name: Run Downloads Script
  ansible.windows.win_shell: C:\ProgramData\EpicGames\Fortnite\downloads.ps1 -Path C:\ProgramData\EpicGames\Fortnite\

- name: Run Inventory Script and Store Output Locally
  ansible.windows.win_shell: C:\ProgramData\EpicGames\Fortnite\scripts\inventory.ps1
  register: inventory

# - name: Store Inventory Script Output on Ansible Box
#   ansible.windows.win_copy:
#     content: "{{ inventory.stdout }}"
#     dest: /opt/inventory/{{ ansible_hostname }}-inventory.txt
#     force: yes

- name: Run Audit Script and Store Output Locally
  ansible.windows.win_shell: C:\ProgramData\EpicGames\Fortnite\scripts\audit.ps1
  register: audit

# - name: Store Audit Script Output on Ansible Box
#   ansible.windows.win_copy:
#     content: "{{ audit.stdout }}"
#     dest: /opt/audit/{{ ansible_hostname }}-audit.txt
#     force: yes

- name: Run Logging Script with Wazuh Box's IP 
  ansible.windows.win_shell: C:\ProgramData\EpicGames\Fortnite\scripts\logging.ps1 {{ hostvars['logging']['ansible_host'] }}

- name: Run Backup Script
  ansible.windows.win_shell: C:\ProgramData\EpicGames\Fortnite\scripts\backup.ps1